In [ ]:
zadanie 1

In [1]:
import numpy as np

In [8]:
arr= np.array([range(1,101)])
print(f"suma arrajki: {arr.sum()}")
print(f"mediana arrajki: {np.median(arr)}")
print(f"srednia arrajki: {np.mean(arr)}")
print(f"min arrajki: {np.min(arr)}")
print(f"max arrajki: {np.max(arr)}")

suma arrajki: 5050
mediana arrajki: 50.5
srednia arrajki: 50.5
min arrajki: 1
max arrajki: 100


In [ ]:
zadanie 2

In [31]:
before = np.array([100, 250, 75, 320, 180, 450, 90])
after = np.array([80, 200, 60, 280, 150, 400, 75])

roznica = before - after
procent_rabatu = np.round((roznica / before) * 100, 2)
srednia_oszczednosc = np.round(np.mean(roznica), 2)

print(f"roznica per produkt to: {roznica}")
print(f"procent rabatu per produkt to: {procent_rabatu}")
print(f"srednia oszczednosc to: {srednia_oszczednosc}")

roznica per produkt to: [20 50 15 40 30 50 15]
procent rabatu per produkt to: [20.   20.   20.   12.5  16.67 11.11 16.67]
srednia oszczednosc to: 31.43


In [ ]:
zadanie 3 

In [50]:
temps = np.array([15, 18, 22, 25, 23, 20, 17, 14, 16, 19, 21, 24])
temps_parzyste = temps[temps % 2 == 0]
temps_ostatnie_5 = temps[-5:]
temps_odwrotna_kolejnosc = temps[::-1]
temps_wyższe_niż_20 = temps[temps > 20]
print(f"temperatury parzyste: {temps_parzyste}")
print(f"temperatury ostatnie 5: {temps_ostatnie_5}")
print(f"temperatury w odwrotnej kolejności: {temps_odwrotna_kolejnosc}")
print(f"temperatury wyższe niż 20: {temps_wyższe_niż_20}")

temperatury parzyste: [18 22 20 14 16 24]
temperatury ostatnie 5: [14 16 19 21 24]
temperatury w odwrotnej kolejności: [24 21 19 16 14 17 20 23 25 22 18 15]
temperatury wyższe niż 20: [22 25 23 21 24]


In [ ]:
zadanie 4

In [82]:
np.random.seed(1)
randomowa_array = np.random.randint(1, 50, size=(5, 4))
print(randomowa_array)
randomowa_array.shape
drugi_wiersz = randomowa_array[1:2]
trzecia_kolumna = randomowa_array[:,2:3]
element = randomowa_array[2, 3]
print(f"drugi wiersz: {drugi_wiersz}")
print(f"trzecia kolumna: {trzecia_kolumna}")
print(f"element w trzecim wierszu i czwartej kolumnie: {element}")
print(f"kształt tablicy: {randomowa_array.shape}")


[[38 44 13  9]
 [10 12  6 16]
 [ 1 17  2 13]
 [ 8 46  7 26]
 [21 38 19 21]]
drugi wiersz: [[10 12  6 16]]
trzecia kolumna: [[13]
 [ 6]
 [ 2]
 [ 7]
 [19]]
element w trzecim wierszu i czwartej kolumnie: 13
kształt tablicy: (5, 4)


In [ ]:
zadanie 5

SyntaxError: invalid syntax (2544559569.py, line 1)

In [79]:
np.random.seed(1)
sales = np.random.randint(10, 100, size=(4, 7))
sales

array([[47, 22, 82, 19, 85, 15, 89],
       [74, 26, 11, 86, 81, 16, 35],
       [60, 30, 28, 94, 21, 38, 39],
       [24, 60, 78, 97, 97, 96, 23]], dtype=int32)

In [94]:
sales_per_produkt = np.mean(sales,axis=1)
sales_per_day = np.mean(sales,axis=0)
day_with_highest_sales = np.argmax(sales_per_day,axis=0)
product_with_lowest_sales = np.argmin(sales_per_produkt,axis=0)
print(f"średnia sprzedaż per produkt: {sales_per_produkt}"
      )
print(f"średnia sprzedaż per dzień: {sales_per_day}"
      )
print(f"dzień z najwyższą sprzedażą: {day_with_highest_sales}"
      )
print(f"produkt z najniższą sprzedażą: {product_with_lowest_sales}"
      )




średnia sprzedaż per produkt: [51.28571429 47.         44.28571429 67.85714286]
średnia sprzedaż per dzień: [51.25 34.5  49.75 74.   71.   41.25 46.5 ]
dzień z najwyższą sprzedażą: 3
produkt z najniższą sprzedażą: 2


In [ ]:
zadanie 6

In [109]:
grades = np.array([78, 45, 92, 67, 34, 88, 56, 91, 23, 85, 73, 95])


print(f"indeksy ocen powyżej 80: {np.where(grades >= 80)}")
print(f"indeksy ocen poniżej 50: {np.where(grades < 50)}")
print(f"liczba ocen w przedziale 60-80: {len(grades[(grades >= 60) & (grades <= 80)])}")
print(f"oceny z zastąpieniem poniżej 50: {np.where(grades >= 50, grades, 50)}")
    

indeksy ocen powyżej 80: (array([ 2,  5,  7,  9, 11]),)
indeksy ocen poniżej 50: (array([1, 4, 8]),)
liczba ocen w przedziale 60-80: 3
oceny z zastąpieniem poniżej 50: [78 50 92 67 50 88 56 91 50 85 73 95]


In [ ]:
zadanie 7

In [119]:
macierz_0 = np.zeros([3,3])
macierz_1 = np.ones([4,4])
macierz_indent = np.eye(5)
macerz_7 = np.full([3,4],7)
wektor_10 = np.linspace(0,1,10)

In [120]:
wektor_10

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
zadanie 8

In [142]:
arr = np.arange(1, 13)
arr = arr.reshape(3, 4)
arr = arr.reshape(2, 6)
arr = arr.reshape(4, 3)
arr_1line = arr.ravel()

In [143]:
arr_1line[0] = 100
arr_1line
arr

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12]])

In [ ]:
zadanie 10

In [160]:
exams = np.array([
[78, 85, 92, 88],
[65, 72, 68, 70],
[90, 88, 95, 92],
[55, 60, 58, 62],
[82, 79, 85, 80]
])
bonus = np.array([[5, 10, 5, 10]])
mnoznik_egzaminow = np.array([1.0, 1.1, 0.95, 1.15, 1.0]).reshape(-1,1)
print(mnoznik_egzaminow)
exams_bonus = (exams + bonus)
print(exams_bonus)
student_mnoznik = exams_bonus * mnoznik_egzaminow
print(student_mnoznik)



[[1.  ]
 [1.1 ]
 [0.95]
 [1.15]
 [1.  ]]
[[ 83  95  97  98]
 [ 70  82  73  80]
 [ 95  98 100 102]
 [ 60  70  63  72]
 [ 87  89  90  90]]
[[83.   95.   97.   98.  ]
 [77.   90.2  80.3  88.  ]
 [90.25 93.1  95.   96.9 ]
 [69.   80.5  72.45 82.8 ]
 [87.   89.   90.   90.  ]]


In [163]:

print(f"Ocena przed bonusem i mnoznikiem: {exams}")
print(f"Ocena po bonusem: {exams_bonus}")
print(f"Ocena po bonusem i mnozniku: {student_mnoznik}")
print(f"Roznica przed/po: {student_mnoznik - exams}")

Ocena przed bonusem i mnoznikiem: [[78 85 92 88]
 [65 72 68 70]
 [90 88 95 92]
 [55 60 58 62]
 [82 79 85 80]]
Ocena po bonusem: [[ 83  95  97  98]
 [ 70  82  73  80]
 [ 95  98 100 102]
 [ 60  70  63  72]
 [ 87  89  90  90]]
Ocena po bonusem i mnozniku: [[83.   95.   97.   98.  ]
 [77.   90.2  80.3  88.  ]
 [90.25 93.1  95.   96.9 ]
 [69.   80.5  72.45 82.8 ]
 [87.   89.   90.   90.  ]]
Roznica przed/po: [[ 5.   10.    5.   10.  ]
 [12.   18.2  12.3  18.  ]
 [ 0.25  5.1   0.    4.9 ]
 [14.   20.5  14.45 20.8 ]
 [ 5.   10.    5.   10.  ]]


In [ ]:
zadanie 13

In [164]:
np.random.seed(42)
data = np.concatenate([np.random.randn(100) * 10 + 50,
np.array([150, -50, 200, -100, 180])
])
np.random.shuffle(data)

In [165]:
data

array([  39.42289071,  200.        ,   64.65648769,   53.4361829 ,
        150.        ,   55.42560044,   32.75082167,   30.86719755,
         51.71368281,   58.22544912,   52.41962272,   42.97946906,
         57.67434729,   65.23029856,   48.84351718,   38.49006423,
         49.27989878,   50.97077549,   59.68644991,   38.93665026,
         47.742237  ,   47.65846625,   55.13267433,   53.61395606,
         45.39361229,   47.0099265 ,   53.61636025,   58.21902504,
         32.36959845,   65.38036566,   42.80155792,   50.87047068,
         45.20825762,   60.57122226,   47.0830625 ,   43.98293388,
         50.67528205,   44.55617275,   53.75698018,   63.56240029,
         30.12431085,   35.2147801 ,   53.14247333,   44.70239796,
         51.96861236,   38.03793376,   57.3846658 ,   65.79212816,
         49.64173961,   65.64643656,   41.91506397,   41.60782477,
         51.1092259 ,   52.61055272,   37.7915635 ,   35.87696299,
         59.15402118,   43.9936131 ,   58.12525822,   47.65863

In [167]:
srednia = np.mean(data)
srednia

np.float64(50.249080786722914)

In [169]:
odchylenie_std = np.std(data)
odchylenie_std

np.float64(29.30407880088081)

In [179]:
z_score = (data - srednia) / odchylenie_std
z_score

array([-0.36944311,  5.11024149,  0.49165193,  0.10875968,  3.40399437,
        0.17664843, -0.59712708, -0.66140565,  0.04997946,  0.27219311,
        0.07406962, -0.24807508,  0.25338679,  0.51123319, -0.04796478,
       -0.40127576, -0.03307328,  0.02462779,  0.32204968, -0.38603604,
       -0.0855459 , -0.08840457,  0.16665235,  0.11482617, -0.16569258,
       -0.11053595,  0.11490822,  0.27197389, -0.6101363 ,  0.51635422,
       -0.25414629,  0.02120489, -0.1720178 ,  0.35224248, -0.10804019,
       -0.2138319 ,  0.01454409, -0.19427016,  0.11970686,  0.45431626,
       -0.68675661, -0.51304464,  0.09873685, -0.18928023,  0.05867892,
       -0.41670469,  0.24350143,  0.5304056 , -0.02072548,  0.52543388,
       -0.28439784, -0.29488236,  0.0293524 ,  0.08058509, -0.42511206,
       -0.49044769,  0.30388058, -0.21346747,  0.2687741 , -0.08839897,
       -0.18535928,  0.32440434,  4.42774264, -0.01310579, -0.20038016,
       -0.16664089, -0.0067549 , -0.67723617, -0.3541279 , -0.17

In [183]:
outliers = np.abs(z_score) <= 3

In [186]:
data_bez_outlierow = data[outliers]
print(data_bez_outlierow)

[39.42289071 64.65648769 53.4361829  55.42560044 32.75082167 30.86719755
 51.71368281 58.22544912 52.41962272 42.97946906 57.67434729 65.23029856
 48.84351718 38.49006423 49.27989878 50.97077549 59.68644991 38.93665026
 47.742237   47.65846625 55.13267433 53.61395606 45.39361229 47.0099265
 53.61636025 58.21902504 32.36959845 65.38036566 42.80155792 50.87047068
 45.20825762 60.57122226 47.0830625  43.98293388 50.67528205 44.55617275
 53.75698018 63.56240029 30.12431085 35.2147801  53.14247333 44.70239796
 51.96861236 38.03793376 57.3846658  65.79212816 49.64173961 65.64643656
 41.91506397 41.60782477 51.1092259  52.61055272 37.7915635  35.87696299
 59.15402118 43.9936131  58.12525822 47.65863043 44.81729782 59.75545127
 49.86502775 44.37712471 45.36582307 50.05113457 30.40329876 39.8716888
 44.98242956 60.30999522 60.03532898 23.80254896 43.54880245 35.36485052
 47.65412867 43.23078    53.57112572 40.91975924 54.96714153 56.11676289
 64.77894045 46.07891847 47.80328112 59.31280119 56.4

In [189]:
odchylenie_std_bez_outlierow =np.std(data_bez_outlierow)
print(f"Odchylenie standardowe przed usunięciem outlierów: {odchylenie_std}")
print(f"Odchylenie standardowe po usunięciu outlierów: {odchylenie_std_bez_outlierow}")

Odchylenie standardowe przed usunięciem outlierów: 29.30407880088081
Odchylenie standardowe po usunięciu outlierów: 9.036161766446297


In [195]:
sredina_data_bez_outlierow = np.mean(data_bez_outlierow)
min_data_bez_outlierow = np.min(data_bez_outlierow)
max_data_bez_outlierow = np.max(data_bez_outlierow)
liczba_elementow_bez_outlierow = len(data_bez_outlierow)
print(f"Średnia przed usunieciem outlierow to: {srednia}, a po to {sredina_data_bez_outlierow}")
print(f"Min przed usunieciem outlierow to: {np.min(data)}, a po to {min_data_bez_outlierow}")
print(f"Max przed usunieciem outlierow to: {np.max(data)}, a po to {max_data_bez_outlierow}")
print(f"Liczba elementow przed usunieciem outlierow to: {len(data)}, a po to {liczba_elementow_bez_outlierow}") 


Średnia przed usunieciem outlierow to: 50.249080786722914, a po to 48.96153482605905
Min przed usunieciem outlierow to: -100.0, a po to 23.802548959102555
Max przed usunieciem outlierow to: 200.0, a po to 68.52278184508938
Liczba elementow przed usunieciem outlierow to: 105, a po to 100


In [197]:

def tekstowy_histogram(dane, liczba_binow=10, szerokosc=50, tytul=""):
    licznosci, krawedzie = np.histogram(dane, bins=liczba_binow)
    max_licznosc = np.max(licznosci)
    
    print(f"\n{tytul}")
    print("-" * 60)
    for i in range(len(licznosci)):
        przedzial = f"{krawedzie[i]:6.1f} - {krawedzie[i+1]:6.1f}"
        dlugosc_slupka = int((licznosci[i] / max_licznosc) * szerokosc)
        slupek = "█" * dlugosc_slupka
        print(f"{przedzial} | {slupek} {licznosci[i]}")
tekstowy_histogram(data, liczba_binow=10, tytul="Dane ORYGINALNE (z outlierami)")
tekstowy_histogram(data_bez_outlierow, liczba_binow=10, tytul="Dane BEZ outlierów")


Dane ORYGINALNE (z outlierami)
------------------------------------------------------------
-100.0 -  -70.0 |  1
 -70.0 -  -40.0 |  1
 -40.0 -  -10.0 |  0
 -10.0 -   20.0 |  0
  20.0 -   50.0 | ██████████████████████████████████████████████████ 54
  50.0 -   80.0 | ██████████████████████████████████████████ 46
  80.0 -  110.0 |  0
 110.0 -  140.0 |  0
 140.0 -  170.0 |  1
 170.0 -  200.0 | █ 2

Dane BEZ outlierów
------------------------------------------------------------
  23.8 -   28.3 | ██ 1
  28.3 -   32.7 | █████████ 4
  32.7 -   37.2 | ██████████████ 6
  37.2 -   41.7 | ███████████████████ 8
  41.7 -   46.2 | █████████████████████████████████████████████ 19
  46.2 -   50.6 | ████████████████████████████████████████ 17
  50.6 -   55.1 | ██████████████████████████████████████████████████ 21
  55.1 -   59.6 | ██████████████████████████ 11
  59.6 -   64.1 | ██████████████ 6
  64.1 -   68.5 | ████████████████ 7
