In [ ]:
zadanie 1

In [20]:
import numpy as np
v1 = np.array([3, 4])
v2 = np.array([1, 2])
v_suma = v1 + v2
roznica = v1 - v2
norma_v1 = np.linalg.norm(v1)
norma_v2 = np.linalg.norm(v2)
print(f"suma to {v_suma}, roznica {roznica}, normav1 to {norma_v1}, a normav2 to {norma_v2} ")


suma to [4 6], roznica [2 2], normav1 to 5.0, a normav2 to 2.23606797749979 


In [ ]:
def narysuj_wektory_2d(vektory_z_etykietami, xlim=(-1, 5), ylim=(-1, 5)):
    x_min, x_max = xlim
    y_min, y_max = ylim
    width = x_max - x_min + 1
    height = y_max - y_min + 1

    # Siatka (pusta)
    grid = [[' .' for _ in range(width)] for _ in range(height)]

    # Oś X i Y
    for row in range(height):
        y_val = y_max - row
        if y_val == 0:
            grid[row] = [' -' for _ in range(width)]

    for col in range(width):
        x_val = x_min + col
        for row in range(height):
            if x_val == 0:
                grid[row][col] = ' |' if grid[row][col] != ' -' else ' +'

    # Umieść symbol w punkcie (x, y)
    for vec, symbol in vektory_z_etykietami:
        x, y_c = int(vec[0]), int(vec[1])
        col = x - x_min
        row = y_max - y_c
        if 0 <= col < width and 0 <= row < height:
            grid[row][col] = f' {symbol}'

    print(f" y={y_max}" + ' ' * (width * 2 - 5) + f"y={y_min}")
    for row in range(height):
        y_val = y_max - row
        prefix = f"y={y_val:2d} |"
        print(prefix + ''.join(grid[row]))
    print("     " + ''.join(f"{x_min + c:2d}" for c in range(width)))
    print(f" (x={x_min} .. x={x_max})")


narysuj_wektory_2d([(v1, 'A'), (v2, 'B'), (v_suma, 'S')])


 y=5         y=-1
y= 5 | . | . . . . .
y= 4 | . | . . A . .
y= 3 | . | . . . . .
y= 2 | . | B . . . .
y= 1 | . | . . . . .
y= 0 | - + - - - - -
y=-1 | . | . . . . .
     -1 0 1 2 3 4 5
 (x=-1 .. x=5)

Legenda: A = v1 = [2, 3], B = v2 = [1, 1], S = v1+v2 = [3, 4]
Obserwuj 'równoległobok': 0 → A → S oraz 0 → B → S tworzą dwie drogi do punktu S.


In [ ]:
zadanie 2

In [4]:
import numpy as np

def make_synthetic_flowers(seed=42):
    """Generuje syntetyczny dataset kwiatów (150 x 4) z 3 gatunkami."""
    rng = np.random.default_rng(seed)
    n_per_class = 50
    centers = np.array([
        [5.0, 3.4, 1.5, 0.2],
        [5.9, 2.8, 4.3, 1.3],
        [6.6, 3.0, 5.6, 2.0],
    ])
    stds = np.array([0.35, 0.35, 0.45, 0.25])
    X_list, y_list = [], []
    for class_idx, center in enumerate(centers):
        samples = rng.normal(loc=center, scale=stds, size=(n_per_class, 4))
        X_list.append(samples)
        y_list.append(np.full(n_per_class, class_idx))
    X = np.vstack(X_list)
    y = np.concatenate(y_list)
    feature_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
    target_names = np.array(['gatunek_A', 'gatunek_B', 'gatunek_C'])
    return X, y, feature_names, target_names



X, y, feature_names, target_names = make_synthetic_flowers(seed=42)


petal_length = X[:, 2]


min_val = petal_length.min()
max_val = petal_length.max()

petal_length_norm = (petal_length - min_val) / (max_val - min_val)

print(f"Min: {min_val:.4f}, Max: {max_val:.4f}\n")
print("Przed normalizacją (pierwsze 10):")
print(np.round(petal_length[:10], 4))

print("\nPo normalizacji (pierwsze 10):")
print(np.round(petal_length_norm[:10], 4))

print(f"\nMin po normalizacji: {petal_length_norm.min():.6f}")
print(f"Max po normalizacji: {petal_length_norm.max():.6f}")

Min: 0.5406, Max: 6.6892

Przed normalizacją (pierwsze 10):
[1.8377 1.5575 1.8957 1.7104 1.8953 2.0501 1.7395 2.4637 1.7772 1.129 ]

Po normalizacji (pierwsze 10):
[0.211  0.1654 0.2204 0.1903 0.2203 0.2455 0.195  0.3128 0.2011 0.0957]

Min po normalizacji: 0.000000
Max po normalizacji: 1.000000


In [ ]:
zadanie 3

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
iloczyn_skalarny = a @ b
norma_a = np.linalg.norm(a)
norma_b = np.linalg.norm(b)
cos_theta = iloczyn_skalarny / (norma_a * norma_b)
cos_theta
kat_rad = np.arccos(cos_theta)
kat_deg = np.degrees(kat_rad)

print(f"Iloczyn skalarny (a·b): {iloczyn_skalarny}")
print(f"Norma a: {norma_a:.2f}")
print(f"Norma b: {norma_b:.2f}")
print(f"cos(theta): {cos_theta:.2f}")
print(f"Kąt w radianach: {kat_rad:.2f}")
print(f"Kąt w stopniach: {kat_deg:.2f}")


Iloczyn skalarny (a·b): 32
Norma a: 3.74
Norma b: 8.77
cos(theta): 0.97
Kąt w radianach: 0.23
Kąt w stopniach: 12.93


In [ ]:
zadanie 4

In [35]:
macierz = np.arange(1, 13).reshape(3, 4)
macierz.shape

(3, 4)

In [36]:
macierz.T.shape

(4, 3)

In [ ]:
macierz.reshape(2,6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [39]:
macierz.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
zadanie 5

In [45]:
macierz1 = np.eye(5)
print(macierz1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [47]:
macierz2 = np.diag([1, 2, 3, 4, 5])
print(macierz2)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [49]:
macierz3 = macierz1 * macierz2
macierz3

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [58]:
macierz4 = macierz1 @ macierz2
print(wynik)
np.array_equal(macierz3, macierz4)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


True

In [ ]:
zadanie 6

In [68]:
v = np.array([3, 4, 12, 0, 5])
norma_l1 = np.linalg.norm(v, ord=1)
norma_l2 = np.linalg.norm(v, ord=2)
print(f"Norma L1:   {norma_l1}, Norma L2:   {norma_l2}")
v_normalized = v / norma_l2
print(f"normalized v2 {v_normalized}")
norma_po_normalizacji = np.linalg.norm(v_normalized)
print(f"norma  po normalizacji v2 to: {norma_po_normalizacji}")

Norma L1:   24.0, Norma L2:   13.92838827718412
normalized v2 [0.21538745 0.28718326 0.86154979 0.         0.35897908]
norma  po normalizacji v2 to: 1.0


In [ ]:
zadanie 7

In [83]:
X, y, feature_names, target_names = make_synthetic_flowers(seed=42)


obs_pierwsza = X[0]
obs_ostatnia = X[-1]

print(f"x0 to {obs_pierwsza}")
print(f"x01 to {obs_ostatnia}")
diff = obs_pierwsza - obs_ostatnia
print(f"diff to {diff}")

odleglosc_L2 = np.linalg.norm(diff, ord=2)


odleglosc_L1 = np.linalg.norm(diff, ord=1)

print(f"Odległość euklidesowa (L2): {odleglosc_L2:.4f}")
print(f"Odległość Manhattan (L1): {odleglosc_L1:.4f}")

x0 to [5.10665098 3.03600556 1.83770304 0.43514118]
x01 to [6.41779406 3.28441045 5.70874687 1.55625949]
diff to [-1.31114308 -0.24840489 -3.87104384 -1.12111831]
Odległość euklidesowa (L2): 4.2453
Odległość Manhattan (L1): 6.5517


In [ ]:
zadanie 8

In [18]:
import numpy as np
np.random.seed(0)
losowa_macierz = np.random.randn(4, 3)
losowa_wektora = np.random.randn(3)
print(f" macierz {losowa_macierz}")
print(f" wektor {losowa_wektora}")

 macierz [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]]
 wektor [0.76103773 0.12167502 0.44386323]


In [26]:
y = losowa_macierz @ losowa_wektora
y


array([1.82562532, 1.49886169, 0.65882168, 0.97550599])

In [ ]:
print(losowa_macierz.shape)
print(losowa_wektora.shape)
print(y.shape)

# ma ksztalt y (4,) z racji, ze iloczyn skalarny jest wykonywany po calych wierszach, w przypadku tylko 1 wiersza w wektorze jest to splaszczane do jednego wymiaru

(4, 3)
(3,)
(4,)


In [ ]:
zadanie 11

In [14]:
import pandas as pd
X, y, feature_names, target_names = make_synthetic_flowers(seed=42)


cov_matrix = np.cov(X, rowvar=False)
cov_df = pd.DataFrame(cov_matrix, index=feature_names, columns=feature_names)
print("Macierz kowariancji:")
cov_df


Macierz kowariancji:


,sepal_length,sepal_width,petal_length,petal_width
sepal_length,0.569072,-0.105687,1.104592,0.501855
sepal_width,-0.105687,0.176168,-0.317585,-0.126906
petal_length,1.104592,-0.317585,3.004024,1.255777
petal_width,0.501855,-0.126906,1.255777,0.597162


In [25]:
cor_matrix = np.corrcoef(X, rowvar=False)
cor_df = pd.DataFrame(cor_matrix, index=feature_names, columns=feature_names)
cor_df


,sepal_length,sepal_width,petal_length,petal_width
sepal_length,1.000000,-0.333790,0.844824,0.860892
sepal_width,-0.333790,1.000000,-0.436561,-0.391267
petal_length,0.844824,-0.436561,1.000000,0.937594
petal_width,0.860892,-0.391267,0.937594,1.000000


In [ ]:

i, j = np.unravel_index(np.argmax(np.abs(cor_matrix - np.eye(4))), cor_matrix.shape)

print(f"top pair: {feature_names[i]} i {feature_names[j]}")
print(f"korelacja: {cor_matrix[i, j]:.4f}")

print(f"top 10 ({feature_names[i]}, {feature_names[j]}):")
df_para = pd.DataFrame({'feature_names[i]': X[:10, i], feature_names[j]: X[:10, j]})
df_para

top pair: petal_length i petal_width
korelacja: 0.9376
top 10 (petal_length, petal_width):


,petal_length,petal_width
0,1.837703,0.435141
1,1.557528,0.120939
2,1.895729,0.394448
3,1.710379,-0.014823
4,1.895303,0.187519
5,2.050144,0.161368
6,1.739539,0.291361
7,2.463741,0.098396
8,1.777191,0.482243
9,1.128983,0.362648


In [ ]:
zadanie 18

In [63]:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [64]:
fare_pcclass = df[['Fare','Pclass']]
fare_pcclass = fare_pcclass.dropna().reset_index(drop=True)


In [69]:

fare = fare_pcclass['Fare'].to_numpy()
pclass = fare_pcclass['Pclass'].to_numpy()

group_means = np.empty(len(fare))
group_stds = np.empty(len(fare))

for c in [1, 2, 3]:
    mask = pclass == c
    
    mean = fare[mask].mean()
    std = fare[mask].std(ddof=1)
    
    group_means[mask] = mean
    group_stds[mask] = std

fare_normalized_np = (fare - group_means) / group_stds
np.round(fare_normalized_np, 6)

array([-0.545549, -0.164217, -0.488239, -0.396205, -0.477626, -0.44296 ,
       -0.411993,  0.628236, -0.215845,  0.701225,  0.256785, -0.734938,
       -0.477626,  1.494247, -0.49425 , -0.347473,  1.311705, -0.571063,
        0.367159, -0.547671,  0.397828, -0.571063, -0.479392, -0.620751,
        0.628236,  1.503798, -0.547671,  2.281761, -0.492128, -0.490718,
       -0.72    ,  0.795685, -0.503097, -0.757388, -0.025311, -0.410239,
       -0.547315, -0.477626,  0.367159, -0.206641, -0.356639,  0.025178,
       -0.490718,  1.558947, -0.492128, -0.477626,  0.154901, -0.503097,
        0.679534,  0.350178,  2.208494, -0.498852, -0.094737,  0.397828,
       -0.282921, -0.620751, -0.757388, -0.547315,  0.528256,  2.820857,
       -0.547315, -0.053007, -0.008672,  1.207699, -0.72    ,  0.133319,
       -0.757388, -0.468431, -0.488239, -0.425623, -0.757388,  2.820857,
        3.938007,  0.06611 ,  3.635569, -0.511588, -0.490718, -0.477626,
        0.621418, -0.10193 , -0.396968, -0.354517, 

In [67]:
fare_pcclass = df[['Fare', 'Pclass']].dropna()

fare_pcclass['mean_fare'] = (
    fare_pcclass.groupby('Pclass')['Fare'].transform('mean')
)

fare_pcclass['std_fare'] = (
    fare_pcclass.groupby('Pclass')['Fare'].transform('std')
)

fare_pcclass['fare_normalized_pd'] = (
    fare_pcclass['Fare'] - fare_pcclass['mean_fare']
) / fare_pcclass['std_fare']

fare_pcclass

,Fare,Pclass,mean_fare,std_fare,fare_normalized_pd
0,7.2500,3,13.675550,11.778142,-0.545549
1,71.2833,1,84.154687,78.380373,-0.164217
2,7.9250,3,13.675550,11.778142,-0.488239
3,53.1000,1,84.154687,78.380373,-0.396205
4,8.0500,3,13.675550,11.778142,-0.477626
...,...,...,...,...,...
886,13.0000,2,20.662183,13.417399,-0.571063
887,30.0000,1,84.154687,78.380373,-0.690922
888,23.4500,3,13.675550,11.778142,0.829880
889,30.0000,1,84.154687,78.380373,-0.690922
